#!/bin/bash

echo "🚀 Deploy CONSILIENCE Backend"
echo "============================="
echo ""
echo "Choose your backend deployment platform:"
echo ""
echo "1. Railway (Recommended - Easy Node.js + Socket.IO)"
echo "   - Go to: https://railway.app"
echo "   - Connect GitHub repo"
echo "   - Select 'backend' folder as root"
echo "   - Auto-deploys with WebSocket support"
echo ""
echo "2. Render"
echo "   - Go to: https://render.com"
echo "   - New Web Service from GitHub"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo ""
echo "3. Heroku"
echo "   - Create new app"
echo "   - Connect GitHub repo"
echo "   - Set buildpack to Node.js"
echo ""
echo "📋 Environment Variables needed:"
echo "- OPENAI_API_KEY=your_openai_key"
echo "- SOLANA_RPC_URL=https://api.mainnet-beta.solana.com"
echo "- PORT=3001"
echo ""
echo "After deployment, update frontend with backend URL!"