#!/bin/bash

echo "CONSILIENCE Simple Deployment Guide"
echo "=================================="
echo ""
echo "1. FRONTEND DEPLOYMENT (Static Hosting):"
echo "   - Upload 'build/' folder to any static host:"
echo "   - Netlify: drag & drop build folder"
echo "   - Vercel: vercel --prod"
echo "   - GitHub Pages: push build to gh-pages branch"
echo ""
echo "2. BACKEND DEPLOYMENT OPTIONS:"
echo ""
echo "   A) Railway (Recommended - Easy):"
echo "   - Connect GitHub repo to Railway"
echo "   - Deploy backend folder"
echo "   - Add environment variables"
echo ""
echo "   B) Heroku:"
echo "   - heroku create consilience-backend"
echo "   - git subtree push --prefix backend heroku main"
echo ""
echo "   C) DigitalOcean App Platform:"
echo "   - Connect repo and select backend folder"
echo ""
echo "3. DATABASE (Free Options):"
echo "   - MongoDB Atlas (free tier)"
echo "   - PlanetScale (free tier)"
echo "   - Supabase (free tier)"
echo ""
echo "4. ENVIRONMENT VARIABLES NEEDED:"
echo "   Frontend (.env):"
echo "   - REACT_APP_API_URL=https://your-backend-url/api"
echo "   - REACT_APP_WEBSOCKET_URL=wss://your-backend-url"
echo ""
echo "   Backend:"
echo "   - PORT=3001"
echo "   - NODE_ENV=production"
echo "   - DATABASE_URL=your-database-connection-string"
echo ""
echo "Your app is ready to deploy!"
echo "Build folder: $(pwd)/build"